### ISSUE TITLE
SEO checklist for PWA

### ISSUE THREAD

**Issue by Sh4d0v** [Sh4d0v/belloo-x#10]
**Sure that:**.
- [ ] The site works in various browsers and test it in Chrome, Edge, Firefox, Safari and Brave.
- [ ] The app works on mobile devices and tablets and passes Google's test.
- [ ] Content is easy to share and display alternate pages in case of being offline.
- [ ] Page transitions don't take too long - pages should respond immediately when clicked.
- [ ] Each page specifies its canonical URL with link rel =“canonical”.
- [ ] Schema.org metadata is included in the PWA.
- [ ] The site uses cache-first networking.
- [ ] Network Information API is used to show the user when they are offline.
- [ ] The content or interface does not jump when the page loads.
